# Site settings
title: Yiting Liu - Creative Technologist  
email: yiting@yitingliu.com
# id: index
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Yiting's playground where I focus on AR/VR, web, and music. 
  I am a creative technologist designing experiences to foster meaningful 
  interactions through AR/VR, music, and performance, currently in NYC.
# baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "https://www.yitingliu.com" # the base hostname & protocol for your site
# blogurl: "http://yitingliu97.wordpress.com/"

# image: https://www.yitingliu.com/assets/profile_square.jpg
# width: 300
# height: 200

# image:
#   path: https://www.yitingliu.com/assets/profile_square.jpg
#   height: 100
#   width: 100

github_username:  Yitingliu97
instagram_username: yitingintech
linkedin_username: yitingliu97
soundcloud_username: yitingliu

# Contact form settings
contact:
  email: your.email@example.com
  placeholders:
    name: "Your Name"
    email: "your.email@example.com"
    subject: "What would you like to discuss?"
    message: "Your message here..."
  submit_text: "Send Message"
# Build settings
markdown: kramdown
permalink: none

kramdown:
  input: GFM    
  # auto_ids: true

plugins:
  - jekyll-archives